FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libc6-dev \
    gcc-arm-linux-gnueabi \
    libc6-dev-armel-cross \
    gcc-aarch64-linux-gnu \
    libc6-dev-arm64-cross \
    gcc-mips-linux-gnu \
    libc6-dev-mips-cross \
    gcc-mipsel-linux-gnu \
    libc6-dev-mipsel-cross \
    gcc-mips64-linux-gnuabi64 \
    libc6-dev-mips64-cross \
    gcc-powerpc-linux-gnu \
    libc6-dev-powerpc-cross \
    gcc-powerpc64-linux-gnu \
    libc6-dev-ppc64-cross \
    gcc-sparc64-linux-gnu \
    libc6-dev-sparc64-cross \
    gcc-riscv64-linux-gnu \
    libc6-dev-riscv64-cross \
    gcc-m68k-linux-gnu \
    libc6-dev-m68k-cross \
    gcc-sh4-linux-gnu \
    libc6-dev-sh4-cross \
    gcc-s390x-linux-gnu \
    libc6-dev-s390x-cross \
    gcc-i686-linux-gnu \
    libc6-dev-i386-cross \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

COPY build_elfs.sh /build/build_elfs.sh
RUN /build/build_elfs.sh
