#########################################################################
# Auto-generated by codegen/build_src.py - DO NOT EDIT                  #
#                                                                       #
# This file is auto-generated. Do not edit manually.                    #
# Regenerate with: python codegen/build_src.py                          #
#                                                                       #
# WARNING: This file is auto-generated. Any changes will be overwritten.#
#########################################################################

from .arches import A8086 as A8086, ARM as ARM, ARM64 as ARM64, BPF as BPF, CORTEX_M as CORTEX_M, EVM as EVM, HEXAGON as HEXAGON, M680X as M680X, M68K as M68K, MAX as MAX, MIPS as MIPS, MOS65XX as MOS65XX, PPC as PPC, RISCV as RISCV, RISCV64 as RISCV64, S390X as S390X, SH as SH, SPARC as SPARC, SYSTEMZ as SYSTEMZ, SYSZ as SYSZ, TMS320C64X as TMS320C64X, TRICORE as TRICORE, WASM as WASM, X86 as X86, X8664 as X8664, XCORE as XCORE
from .core import LITTLE_ENDIAN as LITTLE_ENDIAN, BIG_ENDIAN as BIG_ENDIAN, NO_MODES as NO_MODES